/**
 * Seeded job/internship/drive catalog — companyName is resolved to a real
 * Company.id at seed time (see repositories/company.repository.js#ensureSeeded
 * and the seeding call in index.js#bootstrap). requiredSkills uses the same
 * skill-name vocabulary as Career Guidance's IndustryRole seed so real
 * matching produces meaningful results end to end.
 */
const JOB_SEED_DATA = [
  {
    companyName: "TechNova Solutions",
    title: "Frontend Developer",
    description: "Build and maintain customer-facing web interfaces using React.",
    requiredSkills: { JavaScript: 80, React: 75, CSS: 60, HTML: 60, Git: 40 },
    employmentType: "FULL_TIME",
    location: "Bengaluru",
    isRemote: false,
    salaryMin: 500000,
    salaryMax: 900000,
  },
  {
    companyName: "TechNova Solutions",
    title: "Backend Developer",
    description: "Design and maintain REST APIs and data layers powering the platform.",
    requiredSkills: { "Node.js": 80, SQL: 70, "REST APIs": 75, Git: 40 },
    employmentType: "FULL_TIME",
    location: "Bengaluru",
    isRemote: true,
    salaryMin: 550000,
    salaryMax: 1000000,
  },
  {
    companyName: "DataSphere Analytics",
    title: "Data Analyst",
    description: "Turn raw client data into actionable dashboards and reports.",
    requiredSkills: { SQL: 80, Python: 60, Statistics: 60, "Data Visualization": 55 },
    employmentType: "FULL_TIME",
    location: "Pune",
    isRemote: false,
    salaryMin: 400000,
    salaryMax: 800000,
  },
  {
    companyName: "DataSphere Analytics",
    title: "Junior Data Scientist",
    description: "Build predictive models for client engagements under senior guidance.",
    requiredSkills: { Python: 80, "Machine Learning": 70, Statistics: 65, SQL: 50 },
    employmentType: "FULL_TIME",
    location: "Pune",
    isRemote: true,
    salaryMin: 550000,
    salaryMax: 1100000,
  },
  {
    companyName: "CloudPeak Systems",
    title: "DevOps Engineer",
    description: "Automate deployment pipelines and manage cloud infrastructure for client accounts.",
    requiredSkills: { Linux: 70, Docker: 75, "CI/CD": 70, AWS: 65, Git: 40 },
    employmentType: "FULL_TIME",
    location: "Hyderabad",
    isRemote: false,
    salaryMin: 500000,
    salaryMax: 1200000,
  },
  {
    companyName: "CloudPeak Systems",
    title: "Cloud Support Engineer",
    description: "Provide L2 support and monitoring for managed cloud infrastructure.",
    requiredSkills: { AWS: 75, Networking: 60, Linux: 55 },
    employmentType: "FULL_TIME",
    location: "Hyderabad",
    isRemote: true,
    salaryMin: 400000,
    salaryMax: 750000,
  },
  {
    companyName: "PixelCraft Studios",
    title: "Mobile App Developer",
    description: "Build cross-platform mobile experiences using React Native.",
    requiredSkills: { JavaScript: 65, "React Native": 70, "REST APIs": 55, Git: 40 },
    employmentType: "FULL_TIME",
    location: "Mumbai",
    isRemote: false,
    salaryMin: 450000,
    salaryMax: 950000,
  },
  {
    companyName: "BrightPath Innovations",
    title: "Full Stack Developer",
    description: "Own features end-to-end across a React frontend and Node.js backend.",
    requiredSkills: { JavaScript: 75, React: 60, "Node.js": 65, SQL: 55, "REST APIs": 65 },
    employmentType: "FULL_TIME",
    location: "Remote",
    isRemote: true,
    salaryMin: 500000,
    salaryMax: 1100000,
  },
  {
    companyName: "QuantEdge Technologies",
    title: "Machine Learning Engineer",
    description: "Deploy and maintain ML models in production for financial-services clients.",
    requiredSkills: { Python: 80, "Machine Learning": 80, "Deep Learning": 60, Statistics: 60 },
    employmentType: "FULL_TIME",
    location: "Bengaluru",
    isRemote: false,
    salaryMin: 700000,
    salaryMax: 1600000,
  },
];

const INTERNSHIP_SEED_DATA = [
  {
    companyName: "TechNova Solutions",
    title: "Frontend Development Intern",
    description: "Assist the frontend team building and testing new UI features.",
    requiredSkills: { JavaScript: 50, React: 40, HTML: 40, CSS: 40 },
    durationWeeks: 12,
    stipend: 15000,
    location: "Bengaluru",
    isRemote: false,
    isPPO: true,
  },
  {
    companyName: "DataSphere Analytics",
    title: "Data Analytics Intern",
    description: "Support the analytics team with data cleaning and dashboard building.",
    requiredSkills: { SQL: 50, Python: 40, Statistics: 35 },
    durationWeeks: 10,
    stipend: 12000,
    location: "Pune",
    isRemote: true,
    isPPO: false,
  },
  {
    companyName: "CloudPeak Systems",
    title: "DevOps Intern",
    description: "Shadow the DevOps team on deployment automation tasks.",
    requiredSkills: { Linux: 40, Docker: 35, Git: 30 },
    durationWeeks: 8,
    stipend: 10000,
    location: "Hyderabad",
    isRemote: false,
    isPPO: false,
  },
  {
    companyName: "BrightPath Innovations",
    title: "Full Stack Intern",
    description: "Ship small features across the stack alongside a mentor engineer.",
    requiredSkills: { JavaScript: 45, "Node.js": 40, SQL: 30 },
    durationWeeks: 12,
    stipend: 15000,
    location: "Remote",
    isRemote: true,
    isPPO: true,
  },
  {
    companyName: "QuantEdge Technologies",
    title: "ML Research Intern",
    description: "Support model experimentation and evaluation for a research pilot.",
    requiredSkills: { Python: 50, "Machine Learning": 40, Statistics: 35 },
    durationWeeks: 12,
    stipend: 18000,
    location: "Bengaluru",
    isRemote: false,
    isPPO: false,
  },
];

const PLACEMENT_DRIVE_SEED_DATA = [
  {
    companyName: "TechNova Solutions",
    title: "TechNova Campus Drive 2026",
    description: "On-campus hiring drive for Frontend and Backend Developer roles.",
    eligibilityCriteria: { minReadinessScore: 60 },
    driveDateOffsetDays: 30,
    registrationDeadlineOffsetDays: 21,
  },
  {
    companyName: "BrightPath Innovations",
    title: "BrightPath Full Stack Hiring Drive",
    description: "Hiring drive for Full Stack Developer and Full Stack Intern positions.",
    eligibilityCriteria: { minReadinessScore: 55 },
    driveDateOffsetDays: 45,
    registrationDeadlineOffsetDays: 35,
  },
];

module.exports = { JOB_SEED_DATA, INTERNSHIP_SEED_DATA, PLACEMENT_DRIVE_SEED_DATA };
